name: UltraClearLag
api: 5.0.0
version: 1.0.0
main: Amirxd\ClearLag\UltraClearLag
description: "The Best Clear Lag Plugin in Pocketmine MP 5"
website: https://github.com/amirxdcy4455
license: MIT

author: Amirxd 